### ISSUE TITLE
Fix Armature does not work in Blender 2.83.8 LTS

### ISSUE THREAD

**Issue by MJH1000** [cmd410/VRoidBones#3]
Hi, sorry to bother you but I get the following errors:

Traceback (most recent call last):
  File "D:\PortableApps\BlenderPortableScripts\addons\VRoidBones-master\__init__.py", line 150, in execute
    simplify_symmetrize_names()
  File "D:\PortableApps\BlenderPortableScripts\addons\VRoidBones-master\__init__.py", line 46, in simplify_symmetrize_names
    children = get_children(armature)
  File "D:\PortableApps\BlenderPortableScripts\addons\VRoidBones-master\util.py", line 15, in get_children
    if obj.parent.name == parent.name:
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

**Comment by cmd410** [comment]
Thanks for your feedback!
Apparently I haven't tested this with other objects in the scene aside from character. Fixed it. Now everything should work in version 1.5
